### ISSUE TITLE
need timestamp for user submissions

### ISSUE THREAD

**Issue by ramcdougal** [mcdougallab/pipeline#25]

**Comment by gmichel** [comment]
Hi Robert,

Some progress, but the following does not return a result set although the equivalent does in mongo shell:

db.pipeline.find({"userdata" : "{$exists:true}"})

Not successful in finding the reason, but I would think we should be able to send this.

Perhaps we should make this a restful query.

George

From: ramcdougal ***@***.***>
Sent: Monday, March 22, 2021 9:46 AM
To: mcdougallab/pipeline ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [mcdougallab/pipeline] need timestamp for user submissions (#25)


-

**Comment by ramcdougal** [comment]
The quotes are in the wrong place. Use:

    db.pipeline.find({"userdata" : {"$exists":True}})

**Comment by gmichel** [comment]
Hi Robert,

Thanks, that almost worked. For some reason True needed to be lower case. (?)

Thus far, I have this:

http://10.5.37.243:8888/getuserdataquery

This should return documents that have any field under userdata.local_user populated.

This does a form submit onload for now.

George

**Comment by ramcdougal** [comment]
Looks good. You'll want to move it to be a plain JSON file, not embedded inside of HTML.

Do this with something like:

```python
response = HttpResponse(json.dumps(my_data))
response["Content-Disposition"] = f"attachment; filename=userdata.json"
return response
```

If you're literally doing this by loading the regular `/query` page, then yes, that would need a lowercase `true` as it takes a JSON-encoded query. The Python term for `True` has a capital; the JavaScript/json `true` is lowercase. When you switch to doing the query directly in Python to output the data, you'll need the capital `True`.

**Comment by ramcdougal** [comment]
Note that the arbitrary query part of the database is protected by a
```python
@csrf_protect
```
This prevents people without a CSRF token from being able to access the page. If you logout and clear any associated cookies, and then load the page, you should see an error message:

![image](https://user-images.githubusercontent.com/6668090/112219520-7d4a3700-8bfb-11eb-83ae-d968c95bbd28.png)

When you do the specific query for getting the submitted data, you can simply omit the `@csrf_protect`.

**Comment by gmichel** [comment]
Hi Robert,

Your comment inspired me so I rewrote it to be a python method instead of the hybrid approach of putting the query in the page.

So I can run this now

curl http://10.5.37.243:8888/getuserdataquery

it calls a new method getdocsforuserdata() (with the True not true) and returns the json.

Have to look at security next, since having it on means I can only get a result when logged in.

George
